# Generated by Django 5.2.7 on 2025-11-05 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BERITA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200, verbose_name='Judul BERITA')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Publish')),
                ('isi_BERITA', models.TextField(verbose_name='Isi BERITA')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='BERITA_images/', verbose_name='Gambar BERITA')),
            ],
            options={
                'verbose_name': 'BERITA',
                'verbose_name_plural': 'BERITA',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, verbose_name='Nama Pemberi Komentar')),
                ('tanggal', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Komentar')),
                ('isi_komentar', models.TextField(verbose_name='Isi Komentar')),
                ('BERITA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='FITURBERITA.berita', verbose_name='BERITA')),
            ],
            options={
                'verbose_name': 'Komentar',
                'verbose_name_plural': 'Komentar',
                'ordering': ['-tanggal'],
            },
        ),
    ]
